import {
  ErrorCode,
  ErrorDomain,
  ErrorSeverity,
  RecoveryAction,
} from "./types.ts";

type ErrorCatalogEntry = {
  code: ErrorCode;
  message: string;
  domain: ErrorDomain;
  severity: ErrorSeverity;
  recoveryAction: RecoveryAction;
  retryable?: boolean;
};

const makeEntry = (
  code: ErrorCode,
  message: string,
  domain: ErrorDomain,
  severity: ErrorSeverity,
  recoveryAction: RecoveryAction,
  retryable?: boolean,
): ErrorCatalogEntry => ({
  code,
  message,
  domain,
  severity,
  recoveryAction,
  retryable,
});

export const ERROR_CATALOG: Record<string, ErrorCatalogEntry> = {
  AUTH_REQUIRED: makeEntry(
    "AUTH_REQUIRED",
    "Veuillez vous reconnecter.",
    "auth",
    "warning",
    "relogin",
  ),
  AUTH_INVALID_CREDENTIALS: makeEntry(
    "AUTH_INVALID_CREDENTIALS",
    "Identifiants invalides ou compte inactif.",
    "auth",
    "warning",
    "relogin",
  ),
  AUTH_SESSION_EXPIRED: makeEntry(
    "AUTH_SESSION_EXPIRED",
    "Votre session a expiré. Veuillez vous reconnecter.",
    "auth",
    "warning",
    "relogin",
  ),
  AUTH_WEAK_PASSWORD: makeEntry(
    "AUTH_WEAK_PASSWORD",
    "Mot de passe trop faible.",
    "auth",
    "warning",
    "retry",
  ),
  AUTH_SAME_PASSWORD: makeEntry(
    "AUTH_SAME_PASSWORD",
    "Le nouveau mot de passe doit être différent.",
    "auth",
    "warning",
    "retry",
  ),
  AUTH_FORBIDDEN: makeEntry(
    "AUTH_FORBIDDEN",
    "Accès non autorisé.",
    "auth",
    "error",
    "relogin",
  ),
  AUTH_ERROR: makeEntry(
    "AUTH_ERROR",
    "Erreur d’authentification.",
    "auth",
    "error",
    "relogin",
  ),
  CLIENT_NOT_CONFIGURED: makeEntry(
    "CLIENT_NOT_CONFIGURED",
    "Client non configuré.",
    "client",
    "fatal",
    "contact_support",
  ),
  CONFIG_INVALID: makeEntry(
    "CONFIG_INVALID",
    "Configuration invalide.",
    "client",
    "error",
    "contact_support",
  ),
  CONFIG_MISSING: makeEntry(
    "CONFIG_MISSING",
    "Configuration manquante.",
    "client",
    "error",
    "contact_support",
  ),
  CONFLICT: makeEntry(
    "CONFLICT",
    "Conflit de mise à jour. Rechargez et réessayez.",
    "db",
    "warning",
    "reload",
  ),
  DB_READ_FAILED: makeEntry(
    "DB_READ_FAILED",
    "Impossible de charger les données.",
    "db",
    "error",
    "retry",
    true,
  ),
  DB_WRITE_FAILED: makeEntry(
    "DB_WRITE_FAILED",
    "Impossible d’enregistrer les données.",
    "db",
    "error",
    "retry",
    true,
  ),
  DRAFT_NOT_FOUND: makeEntry(
    "DRAFT_NOT_FOUND",
    "Brouillon introuvable.",
    "db",
    "warning",
    "reload",
  ),
  DRAFT_SAVE_FAILED: makeEntry(
    "DRAFT_SAVE_FAILED",
    "Échec de sauvegarde du brouillon.",
    "db",
    "error",
    "retry",
  ),
  EDGE_FUNCTION_ERROR: makeEntry(
    "EDGE_FUNCTION_ERROR",
    "Erreur serveur.",
    "edge",
    "error",
    "retry",
    true,
  ),
  EMAIL_REQUIRED: makeEntry(
    "EMAIL_REQUIRED",
    "Email requis.",
    "validation",
    "warning",
    "retry",
  ),
  EMAIL_INVALID: makeEntry(
    "EMAIL_INVALID",
    "Email invalide.",
    "validation",
    "warning",
    "retry",
  ),
  DISPLAY_NAME_EMPTY: makeEntry(
    "DISPLAY_NAME_EMPTY",
    "Nom requis.",
    "validation",
    "warning",
    "retry",
  ),
  DISPLAY_NAME_TOO_LONG: makeEntry(
    "DISPLAY_NAME_TOO_LONG",
    "Nom trop long.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_IDS_INVALID: makeEntry(
    "AGENCY_IDS_INVALID",
    "Agences invalides.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_ID_INVALID: makeEntry(
    "AGENCY_ID_INVALID",
    "Identifiant agence invalide.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_NOT_FOUND: makeEntry(
    "AGENCY_NOT_FOUND",
    "Agence introuvable.",
    "db",
    "warning",
    "reload",
  ),
  AGENCY_NAME_REQUIRED: makeEntry(
    "AGENCY_NAME_REQUIRED",
    "Nom d’agence requis.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_NAME_EMPTY: makeEntry(
    "AGENCY_NAME_EMPTY",
    "Nom d’agence requis.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_NAME_TOO_LONG: makeEntry(
    "AGENCY_NAME_TOO_LONG",
    "Nom d’agence trop long.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_NAME_EXISTS: makeEntry(
    "AGENCY_NAME_EXISTS",
    "Nom d’agence déjà utilisé.",
    "validation",
    "warning",
    "retry",
  ),
  AGENCY_CREATE_FAILED: makeEntry(
    "AGENCY_CREATE_FAILED",
    "Impossible de créer l’agence.",
    "db",
    "error",
    "retry",
    true,
  ),
  AGENCY_UPDATE_FAILED: makeEntry(
    "AGENCY_UPDATE_FAILED",
    "Impossible de modifier l’agence.",
    "db",
    "error",
    "retry",
    true,
  ),
  AGENCY_DELETE_FAILED: makeEntry(
    "AGENCY_DELETE_FAILED",
    "Impossible de supprimer l’agence.",
    "db",
    "error",
    "retry",
    true,
  ),
  AGENCY_LOOKUP_FAILED: makeEntry(
    "AGENCY_LOOKUP_FAILED",
    "Impossible de charger l’agence.",
    "db",
    "error",
    "retry",
    true,
  ),
  AI_CONFIG_MISSING: makeEntry(
    "AI_CONFIG_MISSING",
    "Configuration IA manquante.",
    "edge",
    "warning",
    "contact_support",
  ),
  AI_DIAGNOSTIC_ERROR: makeEntry(
    "AI_DIAGNOSTIC_ERROR",
    "L'analyse par l'IA a échoué. Veuillez vérifier les paramètres du modèle ou la clé API.",
    "edge",
    "error",
    "retry",
    true,
  ),
  AI_PROVIDER_AUTH_FAILED: makeEntry(
    "AI_PROVIDER_AUTH_FAILED",
    "Authentification du fournisseur IA refusee.",
    "edge",
    "warning",
    "retry",
  ),
  AI_PROVIDER_RATE_LIMITED: makeEntry(
    "AI_PROVIDER_RATE_LIMITED",
    "Quota fournisseur IA atteint. Reessayez plus tard.",
    "edge",
    "warning",
    "retry",
    true,
  ),
  AI_PROVIDER_UNAVAILABLE: makeEntry(
    "AI_PROVIDER_UNAVAILABLE",
    "Fournisseur IA indisponible.",
    "edge",
    "error",
    "retry",
    true,
  ),
  AI_QUOTA_EXCEEDED: makeEntry(
    "AI_QUOTA_EXCEEDED",
    "Quota IA interne atteint.",
    "edge",
    "warning",
    "none",
  ),
  AI_RESPONSE_INVALID: makeEntry(
    "AI_RESPONSE_INVALID",
    "Reponse IA invalide.",
    "edge",
    "error",
    "retry",
    true,
  ),
  AI_SECRET_NOT_CONFIGURED: makeEntry(
    "AI_SECRET_NOT_CONFIGURED",
    "Chiffrement des cles IA non configure.",
    "edge",
    "fatal",
    "contact_support",
  ),
  ENTITY_DETACH_FAILED: makeEntry(
    "ENTITY_DETACH_FAILED",
    "Impossible de détacher les entités.",
    "db",
    "error",
    "retry",
    true,
  ),
  MEMBERSHIP_LOOKUP_FAILED: makeEntry(
    "MEMBERSHIP_LOOKUP_FAILED",
    "Impossible de charger les appartenances.",
    "db",
    "error",
    "retry",
    true,
  ),
  MEMBERSHIP_UPSERT_FAILED: makeEntry(
    "MEMBERSHIP_UPSERT_FAILED",
    "Impossible de mettre à jour les appartenances.",
    "db",
    "error",
    "retry",
    true,
  ),
  MEMBERSHIP_DELETE_FAILED: makeEntry(
    "MEMBERSHIP_DELETE_FAILED",
    "Impossible de supprimer les appartenances.",
    "db",
    "error",
    "retry",
    true,
  ),
  MEMBERSHIP_NOT_FOUND: makeEntry(
    "MEMBERSHIP_NOT_FOUND",
    "Appartenance introuvable.",
    "db",
    "warning",
    "reload",
  ),
  METHOD_NOT_ALLOWED: makeEntry(
    "METHOD_NOT_ALLOWED",
    "Méthode non autorisée.",
    "client",
    "error",
    "contact_support",
  ),
  NOT_FOUND: makeEntry(
    "NOT_FOUND",
    "Ressource introuvable.",
    "db",
    "warning",
    "reload",
  ),
  PROFILE_CREATE_FAILED: makeEntry(
    "PROFILE_CREATE_FAILED",
    "Profil non créé.",
    "db",
    "error",
    "retry",
    true,
  ),
  PROFILE_LOOKUP_FAILED: makeEntry(
    "PROFILE_LOOKUP_FAILED",
    "Impossible de charger le profil.",
    "db",
    "error",
    "retry",
    true,
  ),
  PROFILE_UPDATE_FAILED: makeEntry(
    "PROFILE_UPDATE_FAILED",
    "Impossible de mettre à jour le profil.",
    "db",
    "error",
    "retry",
    true,
  ),
  PROFILE_NOT_FOUND: makeEntry(
    "PROFILE_NOT_FOUND",
    "Profil introuvable.",
    "db",
    "warning",
    "reload",
  ),
  PASSWORD_TOO_SHORT: makeEntry(
    "PASSWORD_TOO_SHORT",
    "Le mot de passe doit contenir au moins 8 caractères.",
    "validation",
    "warning",
    "retry",
  ),
  PASSWORD_REQUIRES_DIGIT: makeEntry(
    "PASSWORD_REQUIRES_DIGIT",
    "Le mot de passe doit contenir au moins un chiffre.",
    "validation",
    "warning",
    "retry",
  ),
  PASSWORD_REQUIRES_SYMBOL: makeEntry(
    "PASSWORD_REQUIRES_SYMBOL",
    "Le mot de passe doit contenir au moins un symbole.",
    "validation",
    "warning",
    "retry",
  ),
  PASSWORD_RESET_FAILED: makeEntry(
    "PASSWORD_RESET_FAILED",
    "Échec du changement de mot de passe.",
    "auth",
    "error",
    "retry",
  ),
  // RATE_LIMIT: used by frontend mapEdgeError (status 429 → generic rate limit)
  RATE_LIMIT: makeEntry(
    "RATE_LIMIT",
    "Trop de requêtes. Réessayez plus tard.",
    "edge",
    "warning",
    "retry",
    true,
  ),
  // RATE_LIMITED: used by backend services (explicit rate limit rejection)
  RATE_LIMITED: makeEntry(
    "RATE_LIMITED",
    "Trop de requêtes. Réessayez plus tard.",
    "edge",
    "warning",
    "retry",
    true,
  ),
  RATE_LIMIT_CHECK_FAILED: makeEntry(
    "RATE_LIMIT_CHECK_FAILED",
    "Impossible de vérifier la limite de requêtes.",
    "edge",
    "error",
    "retry",
    true,
  ),
  REQUEST_FAILED: makeEntry(
    "REQUEST_FAILED",
    "La requête a échoué.",
    "edge",
    "error",
    "retry",
    true,
  ),
  INVALID_JSON: makeEntry(
    "INVALID_JSON",
    "Payload JSON invalide.",
    "validation",
    "warning",
    "retry",
  ),
  INVALID_PAYLOAD: makeEntry(
    "INVALID_PAYLOAD",
    "Payload invalide.",
    "validation",
    "warning",
    "retry",
  ),
  PAYLOAD_TOO_LARGE: makeEntry(
    "PAYLOAD_TOO_LARGE",
    "Payload trop volumineux.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_DIFF_FAILED: makeEntry(
    "PRICING_REFERENCE_DIFF_FAILED",
    "Impossible de calculer la comparaison du referentiel.",
    "db",
    "error",
    "retry",
    true,
  ),
  PRICING_REFERENCE_IMPORT_BLOCKING_ANOMALIES: makeEntry(
    "PRICING_REFERENCE_IMPORT_BLOCKING_ANOMALIES",
    "Des anomalies bloquantes empechent l activation du referentiel.",
    "validation",
    "warning",
    "none",
  ),
  PRICING_REFERENCE_IMPORT_EMPTY: makeEntry(
    "PRICING_REFERENCE_IMPORT_EMPTY",
    "Le fichier referentiel est vide.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_HASH_MISMATCH: makeEntry(
    "PRICING_REFERENCE_IMPORT_HASH_MISMATCH",
    "Le hash du fichier referentiel ne correspond pas au fichier analyse.",
    "validation",
    "error",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_INVALID_COLUMNS: makeEntry(
    "PRICING_REFERENCE_IMPORT_INVALID_COLUMNS",
    "Le fichier referentiel ne contient pas les colonnes attendues.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_INVALID_FILE: makeEntry(
    "PRICING_REFERENCE_IMPORT_INVALID_FILE",
    "Le fichier referentiel est invalide.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_FILE_NOT_FOUND: makeEntry(
    "PRICING_REFERENCE_IMPORT_FILE_NOT_FOUND",
    "Fichier d import referentiel introuvable.",
    "db",
    "warning",
    "reload",
  ),
  PRICING_REFERENCE_IMPORT_NOT_FOUND: makeEntry(
    "PRICING_REFERENCE_IMPORT_NOT_FOUND",
    "Import referentiel introuvable.",
    "db",
    "warning",
    "reload",
  ),
  PRICING_REFERENCE_IMPORT_PARSE_FAILED: makeEntry(
    "PRICING_REFERENCE_IMPORT_PARSE_FAILED",
    "Impossible de lire le fichier referentiel.",
    "validation",
    "error",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_SHEET_NOT_FOUND: makeEntry(
    "PRICING_REFERENCE_IMPORT_SHEET_NOT_FOUND",
    "Onglet Excel introuvable dans le fichier referentiel.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_IMPORT_STORAGE_FAILED: makeEntry(
    "PRICING_REFERENCE_IMPORT_STORAGE_FAILED",
    "Impossible d acceder au fichier referentiel stocke.",
    "edge",
    "error",
    "retry",
    true,
  ),
  PRICING_REFERENCE_IMPORT_TOO_LARGE: makeEntry(
    "PRICING_REFERENCE_IMPORT_TOO_LARGE",
    "Le fichier referentiel depasse la limite de 50 MB.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_MAPPING_INVALID: makeEntry(
    "PRICING_REFERENCE_MAPPING_INVALID",
    "Mapping de colonnes referentiel invalide.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_MAPPING_REQUIRED: makeEntry(
    "PRICING_REFERENCE_MAPPING_REQUIRED",
    "Confirmez le mapping des colonnes avant analyse.",
    "validation",
    "warning",
    "retry",
  ),
  PRICING_REFERENCE_PERMISSION_DENIED: makeEntry(
    "PRICING_REFERENCE_PERMISSION_DENIED",
    "Action referentiel reservee aux super administrateurs.",
    "auth",
    "error",
    "relogin",
  ),
  PRICING_REFERENCE_SNAPSHOT_ALREADY_ACTIVE: makeEntry(
    "PRICING_REFERENCE_SNAPSHOT_ALREADY_ACTIVE",
    "Cette version referentiel est deja active.",
    "validation",
    "warning",
    "reload",
  ),
  PRICING_REFERENCE_SNAPSHOT_ACTIVATION_BLOCKED: makeEntry(
    "PRICING_REFERENCE_SNAPSHOT_ACTIVATION_BLOCKED",
    "Activation de la version referentiel impossible.",
    "validation",
    "warning",
    "reload",
  ),
  PRICING_REFERENCE_SNAPSHOT_NOT_FOUND: makeEntry(
    "PRICING_REFERENCE_SNAPSHOT_NOT_FOUND",
    "Snapshot referentiel introuvable.",
    "db",
    "warning",
    "reload",
  ),
  ACTION_REQUIRED: makeEntry(
    "ACTION_REQUIRED",
    "Action requise.",
    "validation",
    "warning",
    "retry",
  ),
  ROLE_INVALID: makeEntry(
    "ROLE_INVALID",
    "Rôle invalide.",
    "validation",
    "warning",
    "retry",
  ),
  USER_NOT_FOUND: makeEntry(
    "USER_NOT_FOUND",
    "Utilisateur introuvable.",
    "db",
    "warning",
    "reload",
  ),
  USER_CREATE_FAILED: makeEntry(
    "USER_CREATE_FAILED",
    "Impossible de créer l’utilisateur.",
    "db",
    "error",
    "retry",
    true,
  ),
  USER_UPDATE_FAILED: makeEntry(
    "USER_UPDATE_FAILED",
    "Impossible de modifier l’utilisateur.",
    "db",
    "error",
    "retry",
    true,
  ),
  USER_DELETE_FAILED: makeEntry(
    "USER_DELETE_FAILED",
    "Impossible de supprimer l’utilisateur.",
    "db",
    "error",
    "retry",
    true,
  ),
  USER_DELETE_SELF_FORBIDDEN: makeEntry(
    "USER_DELETE_SELF_FORBIDDEN",
    "Impossible de supprimer votre propre compte.",
    "validation",
    "warning",
    "none",
  ),
  USER_DELETE_HAS_INTERACTIONS: makeEntry(
    "USER_DELETE_HAS_INTERACTIONS",
    "Impossible de supprimer cet utilisateur car il a cree des interactions.",
    "db",
    "warning",
    "none",
  ),
  USER_DELETE_REFERENCED: makeEntry(
    "USER_DELETE_REFERENCED",
    "Impossible de supprimer cet utilisateur car des donnees y sont rattachees.",
    "db",
    "warning",
    "none",
  ),
  SYSTEM_USER_PROVISION_FAILED: makeEntry(
    "SYSTEM_USER_PROVISION_FAILED",
    "Impossible de preparer le compte systeme pour la suppression.",
    "db",
    "error",
    "retry",
    true,
  ),
  SYSTEM_USER_NOT_FOUND: makeEntry(
    "SYSTEM_USER_NOT_FOUND",
    "Compte systeme introuvable pour finaliser la suppression.",
    "db",
    "error",
    "retry",
    true,
  ),
  USER_DELETE_ANONYMIZATION_FAILED: makeEntry(
    "USER_DELETE_ANONYMIZATION_FAILED",
    "Impossible d'anonymiser les interactions avant suppression.",
    "db",
    "error",
    "retry",
    true,
  ),
  VALIDATION_ERROR: makeEntry(
    "VALIDATION_ERROR",
    "Données invalides.",
    "validation",
    "warning",
    "retry",
  ),
  NETWORK_ERROR: makeEntry(
    "NETWORK_ERROR",
    "Impossible de joindre le serveur. Vérifiez votre connexion.",
    "network",
    "error",
    "retry",
    true,
  ),
  UNKNOWN_ERROR: makeEntry(
    "UNKNOWN_ERROR",
    "Erreur inattendue.",
    "unknown",
    "error",
    "contact_support",
  ),
};

export const getErrorCatalogEntry = (
  code: ErrorCode,
): ErrorCatalogEntry | undefined => ERROR_CATALOG[code];
