import type { ChangeEvent, RefObject } from 'react';
import type { FieldErrors, UseFormSetValue } from 'react-hook-form';

import type { RelationMode } from '@/constants/relations';
import type { AgencyConfig } from '@/services/config';
import type { InteractionFormValues } from '@/schemas/interactionSchema';
import type { CockpitFormLeftPaneProps, CockpitFormRightPaneProps } from '@/components/cockpit/CockpitPaneTypes';
import type { Entity, EntityContact, StatusCategory } from '@/types';

export type UseCockpitPanePropsParams = {
  labelStyle: string;
  footerLabelStyle: string;
  errors: FieldErrors<InteractionFormValues>;
  setValue: UseFormSetValue<InteractionFormValues>;
  channel: InteractionFormValues['channel'];
  channelButtonRef: RefObject<HTMLButtonElement | null>;
  relationOptions: string[];
  entityType: string;
  relationButtonRef: RefObject<HTMLButtonElement | null>;
  relationMode: RelationMode;
  activeAgencyId: string | null;
  entitySearchIndex: { entities: Entity[]; contacts: EntityContact[] };
  entitySearchLoading: boolean;
  onSelectEntityFromSearch: (entity: Entity) => void;
  onSelectContactFromSearch: (contact: EntityContact, entity: Entity | null) => void;
  onOpenClientDialog: () => void;
  onOpenGlobalSearch?: () => void;
  recentEntities: Entity[];
  searchInputRef: RefObject<HTMLInputElement | null>;
  selectedEntity: Entity | null;
  selectedContact: EntityContact | null;
  selectedEntityMeta: string;
  selectedContactMeta: string;
  canConvertToClient: boolean;
  onOpenConvertDialog: () => void;
  onClearSelectedEntity: () => void;
  onClearSelectedContact: () => void;
  companyField: CockpitFormLeftPaneProps['companyField'];
  companyCityField: CockpitFormLeftPaneProps['companyCityField'];
  companyName: string;
  companyCity: string;
  showSuggestions: boolean;
  onShowSuggestionsChange: (show: boolean) => void;
  companySuggestions: string[];
  companyInputRef: RefObject<HTMLInputElement | null>;
  contactSelectValue: string;
  contacts: EntityContact[];
  contactsLoading: boolean;
  onContactSelect: (value: string) => void;
  contactSelectRef: RefObject<HTMLButtonElement | null>;
  onOpenContactDialog: () => void;
  contactFirstNameField: CockpitFormLeftPaneProps['contactFirstNameField'];
  contactLastNameField: CockpitFormLeftPaneProps['contactLastNameField'];
  contactPositionField: CockpitFormLeftPaneProps['contactPositionField'];
  contactPhoneField: CockpitFormLeftPaneProps['contactPhoneField'];
  contactEmailField: CockpitFormLeftPaneProps['contactEmailField'];
  contactFirstNameInputRef: RefObject<HTMLInputElement | null>;
  contactFirstName: string;
  contactLastName: string;
  contactPhone: string;
  contactEmail: string;
  onContactFirstNameChange: (event: ChangeEvent<HTMLInputElement>) => void;
  onContactLastNameChange: (event: ChangeEvent<HTMLInputElement>) => void;
  onContactPhoneChange: (event: ChangeEvent<HTMLInputElement>) => void;
  interactionType: string;
  hasInteractionTypes: boolean;
  interactionTypeHelpId: string;
  interactionTypeRef: RefObject<HTMLButtonElement | null>;
  contactService: string;
  quickServices: string[];
  remainingServices: string[];
  servicePickerOpen: boolean;
  onServicePickerOpenChange: (open: boolean) => void;
  config: AgencyConfig;
  subjectField: CockpitFormRightPaneProps['subjectField'];
  notesField: CockpitFormRightPaneProps['notesField'];
  orderRefField: CockpitFormRightPaneProps['orderRefField'];
  reminderField: CockpitFormRightPaneProps['reminderField'];
  reminderAt: string;
  megaFamilies: string[];
  onToggleFamily: (family: string) => void;
  statusMeta: CockpitFormRightPaneProps['statusMeta'];
  statusCategoryLabel: string | null;
  statusCategoryBadges: Record<StatusCategory, string>;
  statusTriggerRef: CockpitFormRightPaneProps['statusTriggerRef'];
  statusValue: string;
  onStatusChange: (statusId: string) => void;
  statusGroups: CockpitFormRightPaneProps['statusGroups'];
  hasStatuses: boolean;
  statusHelpId: string;
  onSetReminder: CockpitFormRightPaneProps['onSetReminder'];
  onReset: () => void;
};
