import type { CockpitFormLeftPaneProps, CockpitFormRightPaneProps } from '@/components/cockpit/CockpitPaneTypes';
import type { UseCockpitPanePropsParams } from './useCockpitPaneProps.types';

export const useCockpitPaneProps = (params: UseCockpitPanePropsParams) => {
  const leftPaneProps: CockpitFormLeftPaneProps = {
    labelStyle: params.labelStyle,
    errors: params.errors,
    setValue: params.setValue,
    channel: params.channel,
    channelButtonRef: params.channelButtonRef,
    relationOptions: params.relationOptions,
    entityType: params.entityType,
    relationButtonRef: params.relationButtonRef,
    relationMode: params.relationMode,
    activeAgencyId: params.activeAgencyId,
    entitySearchIndex: params.entitySearchIndex,
    entitySearchLoading: params.entitySearchLoading,
    onSelectEntityFromSearch: params.onSelectEntityFromSearch,
    onSelectContactFromSearch: params.onSelectContactFromSearch,
    onOpenClientDialog: params.onOpenClientDialog,
    onOpenGlobalSearch: params.onOpenGlobalSearch,
    recentEntities: params.recentEntities,
    searchInputRef: params.searchInputRef,
    selectedEntity: params.selectedEntity,
    selectedContact: params.selectedContact,
    selectedEntityMeta: params.selectedEntityMeta,
    selectedContactMeta: params.selectedContactMeta,
    canConvertToClient: params.canConvertToClient,
    onOpenConvertDialog: params.onOpenConvertDialog,
    onClearSelectedEntity: params.onClearSelectedEntity,
    onClearSelectedContact: params.onClearSelectedContact,
    companyField: params.companyField,
    companyCityField: params.companyCityField,
    companyName: params.companyName,
    companyCity: params.companyCity,
    showSuggestions: params.showSuggestions,
    onShowSuggestionsChange: params.onShowSuggestionsChange,
    companySuggestions: params.companySuggestions,
    companyInputRef: params.companyInputRef,
    contactSelectValue: params.contactSelectValue,
    contacts: params.contacts,
    contactsLoading: params.contactsLoading,
    onContactSelect: params.onContactSelect,
    contactSelectRef: params.contactSelectRef,
    onOpenContactDialog: params.onOpenContactDialog,
    contactFirstNameField: params.contactFirstNameField,
    contactLastNameField: params.contactLastNameField,
    contactPositionField: params.contactPositionField,
    contactPhoneField: params.contactPhoneField,
    contactEmailField: params.contactEmailField,
    contactFirstNameInputRef: params.contactFirstNameInputRef,
    contactFirstName: params.contactFirstName,
    contactLastName: params.contactLastName,
    contactPhone: params.contactPhone,
    contactEmail: params.contactEmail,
    onContactFirstNameChange: params.onContactFirstNameChange,
    onContactLastNameChange: params.onContactLastNameChange,
    onContactPhoneChange: params.onContactPhoneChange,
    interactionType: params.interactionType,
    hasInteractionTypes: params.hasInteractionTypes,
    interactionTypeHelpId: params.interactionTypeHelpId,
    interactionTypeRef: params.interactionTypeRef,
    interactionTypes: params.config.interactionTypes,
    contactService: params.contactService,
    quickServices: params.quickServices,
    remainingServices: params.remainingServices,
    servicePickerOpen: params.servicePickerOpen,
    onServicePickerOpenChange: params.onServicePickerOpenChange,
    services: params.config.services
  };

  const rightPaneProps: CockpitFormRightPaneProps = {
    labelStyle: params.labelStyle,
    footerLabelStyle: params.footerLabelStyle,
    subjectField: params.subjectField,
    notesField: params.notesField,
    orderRefField: params.orderRefField,
    reminderField: params.reminderField,
    reminderAt: params.reminderAt,
    errors: params.errors,
    families: params.config.families,
    megaFamilies: params.megaFamilies,
    onToggleFamily: params.onToggleFamily,
    statusMeta: params.statusMeta,
    statusCategoryLabel: params.statusCategoryLabel,
    statusCategoryBadges: params.statusCategoryBadges,
    statusTriggerRef: params.statusTriggerRef,
    statusValue: params.statusValue,
    onStatusChange: params.onStatusChange,
    statusGroups: params.statusGroups,
    hasStatuses: params.hasStatuses,
    statusHelpId: params.statusHelpId,
    onSetReminder: params.onSetReminder,
    onReset: params.onReset
  };

  return { leftPaneProps, rightPaneProps };
};
