import type { CockpitLeftEntitySectionsProps } from './CockpitLeftEntitySectionsProps';
import type { CockpitFormLeftPaneProps } from './CockpitPaneTypes';

export const buildCockpitLeftEntitySectionsProps = (
  props: CockpitFormLeftPaneProps
): CockpitLeftEntitySectionsProps => {
  const {
    activeAgencyId,
    entityType,
    entitySearchIndex,
    entitySearchLoading,
    recentEntities,
    relationMode,
    onSelectEntityFromSearch,
    onSelectContactFromSearch,
    onOpenClientDialog,
    onOpenGlobalSearch,
    searchInputRef,
    labelStyle,
    errors,
    selectedEntity,
    selectedEntityMeta,
    canConvertToClient,
    onOpenConvertDialog,
    onClearSelectedEntity,
    companyField,
    companyCityField,
    companyName,
    companyCity,
    showSuggestions,
    onShowSuggestionsChange,
    companySuggestions,
    companyInputRef,
    setValue,
    selectedContact,
    selectedContactMeta,
    contactSelectValue,
    contacts,
    contactsLoading,
    onContactSelect,
    contactSelectRef,
    onOpenContactDialog,
    onClearSelectedContact,
    contactFirstNameField,
    contactLastNameField,
    contactPositionField,
    contactPhoneField,
    contactEmailField,
    contactFirstNameInputRef,
    contactFirstName,
    contactLastName,
    contactPhone,
    contactEmail,
    onContactFirstNameChange,
    onContactLastNameChange,
    onContactPhoneChange
  } = props;

  return {
    search: {
      activeAgencyId,
      entityType,
      entitySearchIndex,
      entitySearchLoading,
      recentEntities,
      relationMode,
      onSelectEntityFromSearch,
      onSelectContactFromSearch,
      onOpenClientDialog,
      onOpenGlobalSearch,
      searchInputRef
    },
    identity: {
      labelStyle,
      errors,
      selectedEntity,
      selectedEntityMeta,
      canConvertToClient,
      onOpenConvertDialog,
      onClearSelectedEntity,
      relationMode,
      companyField,
      companyCityField,
      companyName,
      companyCity,
      showSuggestions,
      onShowSuggestionsChange,
      companySuggestions,
      companyInputRef,
      setValue
    },
    contact: {
      labelStyle,
      errors,
      relationMode,
      selectedEntity,
      selectedContact,
      selectedContactMeta,
      contactSelectValue,
      contacts,
      contactsLoading,
      onContactSelect,
      contactSelectRef,
      onOpenContactDialog,
      onClearSelectedContact,
      contactFirstNameField,
      contactLastNameField,
      contactPositionField,
      contactPhoneField,
      contactEmailField,
      contactFirstNameInputRef,
      contactFirstName,
      contactLastName,
      contactPhone,
      contactEmail,
      onContactFirstNameChange,
      onContactLastNameChange,
      onContactPhoneChange
    }
  };
};
