import type { ChangeEvent, RefObject } from 'react';
import type { FieldErrors, UseFormRegisterReturn, UseFormSetValue } from 'react-hook-form';

import type { Entity, EntityContact } from '@/types';
import type { InteractionFormValues } from '@/schemas/interactionSchema';
import type { AgencyConfig } from '@/services/config';
import type { AgencyStatus, StatusCategory } from '@/types';

export type CockpitFormLeftPaneProps = {
  labelStyle: string;
  errors: FieldErrors<InteractionFormValues>;
  setValue: UseFormSetValue<InteractionFormValues>;
  channel: InteractionFormValues['channel'];
  channelButtonRef: RefObject<HTMLButtonElement | null>;
  relationOptions: string[];
  entityType: string;
  relationButtonRef: RefObject<HTMLButtonElement | null>;
  isInternalRelation: boolean;
  isSolicitationRelation: boolean;
  isClientRelation: boolean;
  isProspectRelation: boolean;
  isSupplierRelation: boolean;
  activeAgencyId: string | null;
  entitySearchIndex: {
    entities: Entity[];
    contacts: EntityContact[];
  };
  entitySearchLoading: boolean;
  onSelectEntityFromSearch: (entity: Entity) => void;
  onSelectContactFromSearch: (contact: EntityContact, entity: Entity | null) => void;
  onOpenClientDialog: () => void;
  onOpenGlobalSearch?: () => void;
  recentEntities: Entity[];
  searchInputRef: RefObject<HTMLInputElement | null>;
  selectedEntity: Entity | null;
  selectedContact: EntityContact | null;
  selectedEntityMeta: string;
  selectedContactMeta: string;
  canConvertToClient: boolean;
  onOpenConvertDialog: () => void;
  onClearSelectedEntity: () => void;
  onClearSelectedContact: () => void;
  companyField: UseFormRegisterReturn;
  companyCityField: UseFormRegisterReturn;
  companyName: string;
  companyCity: string;
  showSuggestions: boolean;
  onShowSuggestionsChange: (show: boolean) => void;
  companySuggestions: string[];
  companyInputRef: RefObject<HTMLInputElement | null>;
  contactSelectValue: string;
  contacts: EntityContact[];
  contactsLoading: boolean;
  onContactSelect: (value: string) => void;
  contactSelectRef: RefObject<HTMLButtonElement | null>;
  onOpenContactDialog: () => void;
  contactFirstNameField: UseFormRegisterReturn;
  contactLastNameField: UseFormRegisterReturn;
  contactPositionField: UseFormRegisterReturn;
  contactPhoneField: UseFormRegisterReturn;
  contactEmailField: UseFormRegisterReturn;
  contactFirstNameInputRef: RefObject<HTMLInputElement | null>;
  contactFirstName: string;
  contactLastName: string;
  contactPhone: string;
  contactEmail: string;
  onContactFirstNameChange: (event: ChangeEvent<HTMLInputElement>) => void;
  onContactLastNameChange: (event: ChangeEvent<HTMLInputElement>) => void;
  onContactPhoneChange: (event: ChangeEvent<HTMLInputElement>) => void;
  interactionType: string;
  hasInteractionTypes: boolean;
  interactionTypeHelpId: string;
  interactionTypeRef: RefObject<HTMLButtonElement | null>;
  interactionTypes: string[];
  contactService: string;
  quickServices: string[];
  remainingServices: string[];
  servicePickerOpen: boolean;
  onServicePickerOpenChange: (open: boolean) => void;
  services: string[];
};

export type CockpitFormRightPaneProps = {
  labelStyle: string;
  footerLabelStyle: string;
  subjectField: UseFormRegisterReturn;
  notesField: UseFormRegisterReturn;
  orderRefField: UseFormRegisterReturn;
  reminderField: UseFormRegisterReturn;
  reminderAt: string;
  errors: FieldErrors<InteractionFormValues>;
  families: string[];
  megaFamilies: string[];
  onToggleFamily: (family: string) => void;
  statusMeta: AgencyStatus | null;
  statusCategoryLabel: string | null;
  statusCategoryBadges: Record<StatusCategory, string>;
  statusTriggerRef: RefObject<HTMLButtonElement | null>;
  statusValue: string;
  onStatusChange: (statusId: string) => void;
  statusGroups: Record<StatusCategory, AgencyConfig['statuses']>;
  hasStatuses: boolean;
  statusHelpId: string;
  onSetReminder: (type: '1h' | 'tomorrow' | '3days' | 'nextWeek') => void;
  onReset: () => void;
};
