import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Trash2 } from 'lucide-react';
import type { AiFeature, AiQuotaPolicy } from '../../../../shared/schemas/ai.schema';
import { Button } from '@/components/ui/inputs/basic/Button';
import { Input } from '@/components/ui/inputs/basic/Input';
import { Switch } from '@/components/ui/inputs/basic/Switch';
import { createAiQuota, deleteAiQuota, getAiMembersAccessOverview, getAiSettings, saveAiQuota } from '@/services/ai';
import { handleUiError } from '@/services/errors/handleUiError';
import { aiMembersAccessKey, aiSettingsKey } from '@/services/query/queryKeys';
import { featureLabels, features, Field, SectionState } from './aiAdminUi';

type Scope = 'global' | 'agency' | 'user'; type Form = { id?: string; scope: Scope; target: string; feature: AiFeature; enabled: boolean; daily: string; monthly: string; tokens: string; cost: string };
const empty: Form = { scope: 'global', target: '', feature: 'assistant.referentiels', enabled: true, daily: '', monthly: '', tokens: '', cost: '' };
const nullable = (v: string) => v.trim() ? Number(v.replace(',', '.')) : null;
export const AiQuotasTab = () => {
  const client = useQueryClient(); const [form, setForm] = useState<Form | null>(null); const settings = useQuery({ queryKey: aiSettingsKey(), queryFn: getAiSettings });
  const members = useQuery({ queryKey: aiMembersAccessKey('assistant.referentiels'), queryFn: () => getAiMembersAccessOverview({ feature: 'assistant.referentiels' }) });
  const names = useMemo(() => new Map((members.data?.members ?? []).flatMap((m) => [[m.user_id, m.display_name], [m.agency_id, m.agency_name]])), [members.data]);
  const refresh = () => client.invalidateQueries({ queryKey: aiSettingsKey() });
  const save = useMutation({ mutationFn: async () => { if (!form) return; const limits = { enabled: form.enabled, daily_call_limit: nullable(form.daily), monthly_call_limit: nullable(form.monthly), daily_token_limit: null, monthly_token_limit: nullable(form.tokens), daily_cost_limit: null, monthly_cost_limit: nullable(form.cost), currency: 'USD' }; if (form.id) return saveAiQuota({ id: form.id, ...limits }); return createAiQuota({ scope: form.scope, feature: form.feature, ...(form.scope === 'agency' ? { agency_id: form.target } : {}), ...(form.scope === 'user' ? { user_id: form.target } : {}), ...limits }); }, onSuccess: async () => { setForm(null); await refresh(); }, onError: (e) => handleUiError(e, 'Impossible de sauvegarder le quota IA.') });
  const remove = useMutation({ mutationFn: deleteAiQuota, onSuccess: refresh, onError: (e) => handleUiError(e, 'Impossible de supprimer le quota IA.') });
  if (settings.isPending || members.isPending) return <SectionState>Chargement des quotas…</SectionState>;
  if (settings.isError || members.isError) return <SectionState>Les quotas n’ont pas pu être chargés.</SectionState>;
  const agencies = [...new Map(members.data.members.map((m) => [m.agency_id, m.agency_name])).entries()];
  const edit = (q: AiQuotaPolicy) => setForm({ id: q.id, scope: q.scope, target: q.user_id ?? q.agency_id ?? '', feature: q.feature ?? 'assistant.referentiels', enabled: q.enabled, daily: q.daily_call_limit?.toString() ?? '', monthly: q.monthly_call_limit?.toString() ?? '', tokens: q.monthly_token_limit?.toString() ?? '', cost: q.monthly_cost_limit?.toString() ?? '' });
  return <div className="space-y-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Politiques de quota</h3><p className="text-xs text-muted-foreground">Les cibles sont affichées par nom et chaque politique est persistée côté serveur.</p></div><Button size="sm" onClick={() => setForm(empty)}><Plus className="mr-1 size-3.5" />Créer</Button></div>
    {form ? <form className="grid gap-3 rounded-md border border-border bg-surface-1 p-4 md:grid-cols-2 xl:grid-cols-4" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}><Field label="Périmètre"><select className="h-9 rounded-md border border-input bg-background px-3 text-xs" disabled={Boolean(form.id)} value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value as Scope, target: '' })}><option value="global">Global</option><option value="agency">Agence</option><option value="user">Membre</option></select></Field><Field label="Fonctionnalité"><select className="h-9 rounded-md border border-input bg-background px-3 text-xs" disabled={Boolean(form.id)} value={form.feature} onChange={(e) => setForm({ ...form, feature: e.target.value as AiFeature })}>{features.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></Field>{form.scope !== 'global' ? <Field label={form.scope === 'agency' ? 'Agence' : 'Membre'}><select required className="h-9 rounded-md border border-input bg-background px-3 text-xs" disabled={Boolean(form.id)} value={form.target} onChange={(e) => setForm({ ...form, target: e.target.value })}><option value="">Sélectionner…</option>{(form.scope === 'agency' ? agencies : members.data.members.map((m) => [m.user_id, `${m.display_name} · ${m.agency_name}`] as const)).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></Field> : null}<Field label="Appels / jour"><Input type="number" min="0" value={form.daily} onChange={(e) => setForm({ ...form, daily: e.target.value })} /></Field><Field label="Appels / mois"><Input type="number" min="0" value={form.monthly} onChange={(e) => setForm({ ...form, monthly: e.target.value })} /></Field><Field label="Tokens / mois"><Input type="number" min="0" value={form.tokens} onChange={(e) => setForm({ ...form, tokens: e.target.value })} /></Field><Field label="Coût / mois (USD)"><Input type="number" min="0" step="any" value={form.cost} onChange={(e) => setForm({ ...form, cost: e.target.value })} /></Field><div className="flex items-center gap-2 text-xs"><Switch aria-label="Politique de quota active" checked={form.enabled} onCheckedChange={(enabled) => setForm({ ...form, enabled })} />Politique active</div><div className="flex gap-2 md:col-span-2 xl:col-span-4"><Button size="sm" type="submit" disabled={save.isPending}>Enregistrer le quota</Button><Button size="sm" type="button" variant="outline" onClick={() => setForm(null)}>Annuler</Button></div></form> : null}
    <div className="divide-y divide-border rounded-md border border-border">{settings.data.quotas.length ? settings.data.quotas.map((quota) => <div key={quota.id} className="grid items-center gap-3 p-3 md:grid-cols-[1fr_1fr_auto]"><button type="button" className="min-w-0 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" onClick={() => edit(quota)}><p className="text-xs font-semibold">{quota.scope === 'global' ? 'Global' : names.get(quota.user_id ?? quota.agency_id ?? '') ?? 'Cible supprimée'}</p><p className="text-[11px] text-muted-foreground">{quota.feature ? featureLabels[quota.feature] : 'Toutes les fonctionnalités'}</p></button><p className="text-[11px] tabular-nums text-muted-foreground">{quota.monthly_call_limit ?? '∞'} appels · {quota.monthly_token_limit ?? '∞'} tokens · {quota.monthly_cost_limit ?? '∞'} USD / mois</p><Button size="icon" variant="ghost" aria-label="Supprimer ce quota" onClick={() => { if (window.confirm('Supprimer cette politique de quota ?')) remove.mutate({ id: quota.id }); }}><Trash2 className="size-3.5" /></Button></div>) : <SectionState>Aucune politique de quota configurée.</SectionState>}</div>
  </div>;
};
